### ISSUE TITLE
State of Zutre?

### ISSUE THREAD

**Issue by Anachron** [maclisowski/zutre#42]
I‘m looking for Spectre on Vue and just found this library.

What‘s the state? Is this still in development? Thanks.

**Comment by maclisowski** [comment]
Hi @Anachron , 
Am really sorry for late reply - had some private issues to solve for over last month. Yes this is still in development, there was few updates in Spectre and Vue itself - I will be back to development of this project by the end of this month and will try to update and code improvements during the next month and make it ready to be used with projects. 
I have already start to work on some private project based on Zutre and it works pretty fine, there is some small issues which am going to fix. 
If you could spend some time to play around and provide some feedback I would appreciate it much!

**Comment by Vectrex** [comment]
Good to read. Since I use spectre.css and have switched to vue I hope I find time to be of help.

**Comment by maclisowski** [comment]
will close this task. If there would be any more questions please create new ticket
